### ISSUE TITLE
Routing -> history::previous doesn't work?

### ISSUE THREAD

**Issue by hwchen** [seed-rs/seed#296] opened 2019-11-27 21:16 UTC
I'm not sure if I'm doing the routing correctly but I'm having trouble getting the `previous` button in the browser to work properly.

Here's the [example](https://github.com/hwchen/frontend-counter-test-rs/blob/master/seed-route/src/lib.rs)

In order:
- When I load the index page, I see "one" and a button to go to page two.
- When I click the button, I go to page two and see "two"
- When I click `previous page` in the browser, the url changes to the root path, but the page still renders "two" (Here I expect it to render page one)
- When I then press enter in the address bar (where the root path is displayed) I get page one.

I tried following the example from the guide. It basically made sense, but I'm not able to get the behavior I expect. I may have just messed up something.

Thanks!

**Comment by MartinKavik** [comment] 2019-11-28 01:09
I think the browser automatically pushes initial url into history without data => the initial url isn't associated with the `seed::Url` (aka data / state) so once you get back to initial url, history returns empty state and the handler isn't called because of this line:
https://github.com/seed-rs/seed/blob/e29041f431c361dad7636fb03a41df3985a56435/src/routing.rs#L210

---

As an ugly workaround, try to add this into your example:
```rust
use serde_json;

// ...

#[wasm_bindgen(start)]
pub fn render() {
    seed::App::build(
        |url: Url, _| {
            let title = match &url.title {
                Some(t) => t,
                None => "",
            };
            let data =
                JsValue::from_serde(&serde_json::to_string(&url).expect("Problem serializing route data"))
                    .expect("Problem converting route data to JsValue");

            history().replace_state(&data, title).expect("replace history state");
            Init::new(Model::new())
        },
        update,
        view,
    )
        .routes(routes)
        .build_and_start();
}
```

---

So I think it's a bug and we should resolve it properly once PR https://github.com/seed-rs/seed/pull/290 is merged to prevent merge conflicts.

**Comment by hwchen** [comment] 2019-11-28 04:22
I see, after I did some digging your explanation makes sense. I’ll continue to look around a bit, I think I don’t fully understand yet why you use `data` for the path instead of `path`.

**Comment by MartinKavik** [comment] 2019-11-28 11:20
> I don’t fully understand yet why you use data

@David-OConnor Can we just parse current URL to `seed::Url` and don't use `data` at all? Or is it slow or is the current URL not always synchronized with `data` in the associated history item?

---

A little bit OT:
Do we have to use `clean_url`?
https://github.com/seed-rs/seed/blob/e29041f431c361dad7636fb03a41df3985a56435/src/routing.rs#L151

**Comment by hwchen** [comment] 2019-11-28 17:24
So looking at this line:
```
let data =
                JsValue::from_serde(&serde_json::to_string(&url).expect("Problem serializing route data"))
                    .expect("Problem converting route data to JsValue");

```
I was able to replace `from_serde` with `from_str`, because it looks like you're just using the string representation of `Url`. Not using `from_serde` might save some time https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen/struct.JsValue.html#method.from_serde .

**Comment by hwchen** [comment] 2019-11-28 17:28
Oh, right, that was another confusing thing; I finally realized that https://github.com/seed-rs/seed/blob/e29041f431c361dad7636fb03a41df3985a56435/src/routing.rs#L210 returns `None` if the data is not a string. So when I tried making `data` a json object (while I was poking around), I was able to put it in the history's data, but would get silently bypassed at line 210.

**Comment by MartinKavik** [comment] 2019-11-28 17:31
Yeah, let's wait for @David-OConnor answers and merging of that PR and then we should refactor it.

**Comment by David-OConnor** [comment] 2019-11-29 16:02
> Can we just parse current URL to seed::Url and don't use data at all?
Sure; they should be equivalent

> I was able to replace from_serde with from_str
Nice - in the PR

> Do we have to use clean_url?
After some experimenting, it seems like we don't. I don't remember the cases the required it, and if they're still relevant.

> returns None if the data is not a string. 
I think this was the root cause: https://github.com/seed-rs/seed/pull/300

**Comment by David-OConnor** [comment] 2019-11-30 00:33
Merged

**Closed by David-OConnor** 2019-11-30 00:33 UTC
Labels: bug
