### ISSUE TITLE
Unable to read currently installed version for crate: wasm-pack

### ISSUE THREAD

**Issue by samueller** [seed-rs/seed#347] opened 2020-02-03 06:02 UTC
When running `cargo make build`, I get the following warning:

> [cargo-make] WARN - Unable to read currently installed version for crate: wasm-pack

Everything seems to work though. Curious what the issue is and if there are consequences? Here's the rest of the cargo-make output:

> [cargo-make] INFO - Running Task: create_wasm
> [cargo-make] WARN - Unable to read currently installed version for crate: wasm-pack
> [cargo-make] INFO - Execute Command: "wasm-pack" "build" "--target" "web" "--out-name" "package" "--dev"
> [INFO]: 🎯  Checking for the Wasm target...
> [INFO]: 🌀  Compiling to Wasm...
>     Finished dev [unoptimized + debuginfo] target(s) in 0.07s
> [INFO]: License key is set in Cargo.toml but no LICENSE file(s) were found; Please add the LICENSE file(s) to your project directory
> [INFO]: ⬇️  Installing wasm-bindgen...
> [INFO]: ✨   Done in 0.37s
> [INFO]: 📦   Your wasm pkg is ready to publish at ./pkg.
> [cargo-make] INFO - Running Task: build
> [cargo-make] INFO - Execute Command: "cargo" "build" "--all-features"
>     Finished dev [unoptimized + debuginfo] target(s) in 0.08s
> [cargo-make] INFO - Running Task: end
> [cargo-make] INFO - Build Done in 0 seconds.
>

**Comment by MartinKavik** [comment] 2020-02-03 06:41
It looks like you have this issue with the Rust quickstart (https://github.com/seed-rs/seed-quickstart).
What's your OS, please?

I think the problem is that `cargo-make` can't find `wasm-pack` or parse it's version when the minimal one is defined.
- Related `cargo-make` [docs](https://github.com/sagiegurari/cargo-make/blob/afbb4b2b7242bb1be36e52f1aca2a4f25738aaef/README.md#defining-minimal-version)
- Related `cargo-make` [check in the code](https://github.com/sagiegurari/cargo-make/blob/afbb4b2b7242bb1be36e52f1aca2a4f25738aaef/src/lib/installer/crate_version_check.rs#L149).
- Related [command](https://github.com/seed-rs/seed-quickstart/blob/7cb80b9e86939191da1cb1b583b87c425718dfee/Makefile.toml#L21) in the quickstart.

I can't reproduce it on Windows and maybe it's `cargo-make` bug. Could you investigate it a little bit more? Thanks!

**Comment by samueller** [comment] 2020-02-03 07:03
I'm on macOS Catalina. I'll try to dig in a bit.

**Comment by sagiegurari** [comment] 2020-04-24 10:41
I ran 
```toml
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V", min_version = "0.9.1" }
```
on linux with latest cargo-make, rustc 1.44.0 nightly and it works well.
the information is read from the .crates.toml so maybe you are using an old rust version? which might explain why on different machine it didn't reproduce.

**Comment by MartinKavik** [comment] 2020-04-25 09:31
@samueller Please update your Rust, `wasm-pack` and `cargo-make` version and try it please so we know the issue still exists. 
Otherwise I'll close the issue because CI, where many `cargo-make` commands are executed, runs without problems on Linux and  Mac. 
And I've never noticed any `cargo-make` / build bugs on any platforms and there aren't any similar issues reported by other users => I don't know how to reproduce it.

**Comment by samueller** [comment] 2020-04-26 00:56
@MartinKavik I just updated Rust to v1.43, `wasm-pack` to v0.9.1 (from v0.8.0), `cargo-make` to v0.30.6 (from v0.29.0), and adjusted my `Makefile.toml` to reflect `min_version = "0.9.1"` in the `install_crate`s as per @sagiegurari. Unfortunately, I still get the same `wasm-pack` warning.

Another person on a completely separate machine has the exact same warning and I tried this on another machine too, with the same warning. So, it's not a fluke on my particular machine. It must be our code. Maybe the `Makefile.toml` or `Cargo.toml` files? Though they seem pretty standard.

**Comment by sagiegurari** [comment] 2020-04-26 17:27
@samueller  maybe you can open an issue in the cargo-make repo. seems more related to it.
and we will continue the discussion there.
if possible, provide the following:
* CARGO_HOME env value - if exists only....
* you .cargo directory path
* in the .cargo dir if ".crates.toml" file exists..
* if .crates.toml exists, its content. i'm looking for a structure like:

```toml
[v1]
"cargo-edit 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-add", "cargo-rm", "cargo-upgrade"]
```

for example...

**Comment by flosse** [comment] 2022-06-18 13:39
I assume this is not a problem any more. Feel free to re-open it if not.

**Closed** 2022-06-18 13:38 UTC
Labels: bug
